version: '3.9'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - ./jenkins_data:/var/jenkins_home
  
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    ports:
      - 9000:9000
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions