version: '3.9'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - ./app:/app
      - ./jenkins_data:/var/jenkins_home