version: '3.7'

services:
  redis:
    container_name: redis
    build: ./redis
    ports:
      - 6379:6379
    networks:
      - redis-net
  
  app:
    container_name: app
    build: ./app
    depends_on:
      - redis
    networks:
      - redis-net

networks:
  redis-net:
    name: redis-net
    external: true
